# Use Static provisioning to define a PV for Cloud Storage buckets.
# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#provision-static.
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: my-job-run
  labels:
    kueue.x-k8s.io/queue-name: multislice-queue  # Name of the LocalQueue
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool # 1:1 job replica to node pool assignment
spec:
  failurePolicy:
    maxRestarts: 0
  replicatedJobs:
    - name: slice-job
      replicas: 1
      template:
        spec:
          parallelism: 2    # Equal to the number of VMs per slice
          completions: 2    # Same as the above.
          backoffLimit: 0   # When any pod fails, the job is failed
          template:
            spec:
              schedulerName: default-scheduler
              restartPolicy: Never
              nodeSelector:
                cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
                
              priorityClassName: medium
              hostNetwork: true
              dnsPolicy: ClusterFirstWithHostNet
              terminationGracePeriodSeconds: 30
              containers:
              - name: workload-cpu
                image: gcr.io/my-project/my-container
                
                env: 
                - name: REPLICATED_JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['jobset.sigs.k8s.io/replicatedjob-name']
                - name: JOB_INDEX
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['jobset.sigs.k8s.io/job-index']
                - name: JOB_COMPLETION_INDEX
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
                - name: PROCESSES_IN_JOB
                  value: "2"
                - name: WORLD_SIZE
                  value: "2"
                
                - name: JOBSET_NAME
                  value: "my-job-run"
                - name: COORDINATOR_ADDRESS
                  value: "$(JOBSET_NAME)-$(REPLICATED_JOB_NAME)-0-0.$(JOBSET_NAME)"
                - name: MASTER_PORT
                  value: "1234"
  
                ports:
                - containerPort: 8471
                - containerPort: 8080
                - containerPort: 1234
                securityContext: {}
                  # privileged: true
                command:
                - bash
                - -c
                - |
                  python3 -u /app/model.py --project=my-project --bucket=my-bucket --prefix=fineweb/sample/10BT/00 --num-workers=1 --num-nodes=2 --devices=2 --batch-size=128 --epochs=2 --limit-train-batches=10 --log-level=ERROR;
