name: Continuous Tests

on:
  push:
    branches: [amaloo/pypi-tests]
  pull_request:
    branches: [amaloo/pypi-tests]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.8"
      - name: Create virtual environment
        run: python3 -m venv venv
      - name: Activate virtual environment
        shell: bash
        run: source venv/bin/activate
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install gcs-torch-dataflux
      - name: Run tests
        run: |
          pytest dataflux_pytorch/tests -vv --junit-xml=sponge_log.xml --log-cli-level=DEBUG
